---
title: "nanno_comparison"
author: "Sujung Chung"
date: '2022-03-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(janitor)
library(here)
library(naniar)
library(shiny)
library(lubridate)
library(dplyr)
``` 

## Loading Data
```{r}
nanno1_clean <- readr::read_csv("new_clean_data/nanno1_clean.csv")
```
## Code
```{r}
nanno1_wide <- nanno1_clean %>% 
  pivot_wider(names_from = "flask", values_from= "ph")
nanno1_wide 
```
```{r}
ph7_6<- nanno1_wide %>% 
  select(`pH  7.6...4`,`pH  7.6...6`,`pH  7.6...9`) %>% 
  rowMeans()
```
```{r}
ph8_2<- nanno1_wide %>% 
  select(`pH  8.2...5`,`pH  8.2...7`,`pH  8.2...8`) %>% 
  rowMeans()
```
```{r}
new_nanno_wide<- cbind(nanno1_wide, ph7_6, ph8_2)
new_nanno_wide
```
```{r}
new_nanno_long <- new_nanno_wide%>%
  select(seconds, ph7_6, ph8_2)%>%
  pivot_longer(-seconds,
    names_to = "flask",
    values_to = "ph"
  )
new_nanno_long
```
```{r}
new_nanno_long %>% 
  ggplot(aes(x=seconds, y=ph, color=flask))+
  geom_line()+
  labs(
    title = expression(paste("pH readings of",italic(" N. oculata "))),
    x = "Time (seconds)",
    y= "pH")+
  scale_color_discrete(
    labels = c("ph7_6" = "pH 7.6",
               "ph8_2" = "pH 8.2")
  )
```

